version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
permissions:
  - object: /home/ec2-user/server
    pattern: "**"
    owner: ec2-user
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3600
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 3600
      runas: ec2-user
