version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
permissions:
  - object: /home/ec2-user/scripts/after_install.sh
    owner: ec2-user
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/dep_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 3600
      runas: root
